# 深度学习推荐系统配置文件

# 数据配置
data:
  business_file: "../yelp_business.csv"
  reviews_file: "../reviews_of_restaurants.txt"
  users_file: "../users.txt"
  processed_dir: "../data/processed"
  embeddings_dir: "../data/embeddings"

# 模型配置
model:
  # 推荐模型类型: ncf, deepfm, wide_deep, lightgcn, user_cf, item_cf, svd, nmf
  type: "ncf"
  
  # 文本模型类型: bert, textcnn, bilstm
  text_model: "bert"
  
  # 模型参数
  embed_dim: 64
  mlp_dims: [128, 64, 32]
  dropout: 0.2
  max_length: 512

# 训练配置
training:
  batch_size: 256
  epochs: 50
  learning_rate: 0.001
  weight_decay: 1e-5
  negative_ratio: 1
  val_ratio: 0.2
  
  # 学习率调度
  lr_step_size: 10
  lr_gamma: 0.5
  
  # 早停
  patience: 10
  min_delta: 1e-4

# 推荐配置
recommendation:
  # 推荐数量
  top_k: 10
  
  # 相似度阈值
  similarity_threshold: 0.1
  
  # 冷启动策略: random, popular, content_based
  cold_start_strategy: "popular"

# 评估配置
evaluation:
  # 评估指标
  metrics: ["rmse", "mae", "precision", "recall", "ndcg"]
  
  # 交叉验证折数
  cv_folds: 5
  
  # 测试集比例
  test_ratio: 0.2

# 系统配置
system:
  # 设备: cpu, cuda
  device: "auto"
  
  # 随机种子
  random_seed: 42
  
  # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_level: "INFO"
  
  # 输出目录
  output_dir: "../results"
  
  # 是否使用wandb
  use_wandb: false
  project_name: "yelp-recommendation"

# 特征工程配置
feature_engineering:
  # 文本特征
  text:
    use_bert: true
    bert_model: "bert-base-chinese"
    max_length: 512
    batch_size: 32
  
  # 数值特征
  numerical:
    normalize: true
    method: "standard"  # standard, minmax, robust
  
  # 类别特征
  categorical:
    encoding: "onehot"  # onehot, label, target
    max_categories: 100

# 图神经网络配置 (LightGCN)
gnn:
  num_layers: 3
  dropout: 0.1
  regularization: 1e-4

# 深度推荐网络配置
deep_recommendation:
  # DeepFM配置
  deepfm:
    field_dims: [100, 100, 100]  # 需要根据实际数据调整
    embed_dim: 10
    mlp_dims: [400, 400, 400]
  
  # Wide&Deep配置
  wide_deep:
    wide_dims: 100
    deep_dims: [400, 400, 400]
    embed_dims: [10, 10, 10]

# 实验配置
experiment:
  # 实验名称
  name: "yelp_recommendation_experiment"
  
  # 实验描述
  description: "基于深度学习的Yelp商户推荐系统"
  
  # 实验标签
  tags: ["recommendation", "deep_learning", "yelp", "bert"]
  
  # 超参数搜索
  hyperparameter_search:
    enabled: false
    method: "grid"  # grid, random, bayesian
    n_trials: 10
